[package]
name = "graft"
version = "0.4.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
tree-sitter = "0.22"
tree-sitter-typescript = "0.21"
tree-sitter-python = "0.21"
tree-sitter-go = "0.21"
tree-sitter-rust = "0.21"
tree-sitter-java = "0.21"
tree-sitter-cpp = "0.22"
diffy = "0.4"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
ureq = { version = "2.9", features = ["json"] }